### ISSUE TITLE
How to add Netlogo.jl package?

### ISSUE THREAD

**Issue by sbacelar** [nicolaspayette/NetLogo.jl#1]
I want to run `demo.jl` but first it is necessary to `Pkg.add("NetLogo.jl")`. How can it be done since `NetLogo.jl` is not registered.

**Comment by nicolaspayette** [comment]
You should be able to install the package by running:

```julia
Pkg.clone("git@github.com:nicolaspayette/NetLogo.jl.git")
```

I have updated the README to reflect this.

Thanks for reporting (and being willing to try it out!). Please do not hesitate if you stumble upon anything else.
